//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGym
{
    using System;
    
    public enum EstadoCuota : long
    {
        Cobrado = 0,
        Impaga = 1,
        Parcial = 2,
        Pendiente = 3
    }
}
