//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiniGymModelContainer : DbContext
    {
        public MiniGymModelContainer()
            : base("name=MiniGymModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocalidadSet> Localidades { get; set; }
        public virtual DbSet<ProvinciaSet> Provincias { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<PrestamoSet> Prestamos { get; set; }
        public virtual DbSet<CuotaSet> Cuotas { get; set; }
        public virtual DbSet<PlanSet> Planes { get; set; }
    }
}
