//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public long Id { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Dni { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Cuil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public bool EstaEliminado { get; set; }
        public long LocalidadId { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
    
        public virtual LocalidadSet Localidad { get; set; }
    }
}
