//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrestamoSet()
        {
            this.Cuota = new HashSet<CuotaSet>();
        }
    
        public long Id { get; set; }
        public string CodigoCredito { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public int CantidadCuotas { get; set; }
        public string Notas { get; set; }
        public EstadoPrestamo EstadoPrestamo { get; set; }
        public long PersonaId { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuotaSet> Cuota { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
